package com.intakeflow.config;

import com.intakeflow.domain.*;import com.intakeflow.repository.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.ApplicationArguments;import org.springframework.boot.ApplicationRunner;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;

@Component public class DemoDataInitializer implements ApplicationRunner{
 private final AppUserRepository users;private final FormDefinitionRepository forms;private final FormVersionRepository versions;private final SubmissionRepository submissions;private final PasswordEncoder passwords;private final boolean enabled;
 public DemoDataInitializer(AppUserRepository u,FormDefinitionRepository f,FormVersionRepository v,SubmissionRepository s,PasswordEncoder p,@Value("${app.demo-mode}")boolean enabled){users=u;forms=f;versions=v;submissions=s;passwords=p;this.enabled=enabled;}
 @Override @Transactional public void run(ApplicationArguments args){if(!enabled||users.count()>0)return;var admin=user("admin@intakeflow.demo","Maya Chen",Role.ADMIN);var requester=user("requester@intakeflow.demo","Jordan Lee",Role.REQUESTER);var reviewer=user("reviewer@intakeflow.demo","Priya Shah",Role.REVIEWER);users.saveAll(List.of(admin,requester,reviewer));var def=new FormDefinition();def.setSlug("vendor-onboarding-request");def.setCreatedBy(admin);forms.save(def);var version=new FormVersion();version.setForm(def);version.setVersionNumber(1);version.setTitle("Vendor Onboarding Request");version.setDescription("Collect the operational and compliance details required to onboard a new vendor.");version.setStatus(FormVersionStatus.PUBLISHED);version.setPublishedAt(Instant.now().minus(Duration.ofDays(14)));add(version,"vendor_name","Vendor name","Registered business name",FieldType.TEXT,true,List.of());add(version,"employee_count","Number of employees","Approximate global headcount",FieldType.NUMBER,true,List.of());add(version,"service_category","Service category","Select the closest category",FieldType.DROPDOWN,true,List.of("Technology","Professional services","Facilities","Marketing"));add(version,"start_date","Requested start date","When should onboarding be complete?",FieldType.DATE,true,List.of());versions.save(version);sample(version,requester,reviewer,"REQ-20260818-A7D2F1",SubmissionStatus.SUBMITTED,"Northstar Analytics","180","Technology","2026-09-15",null);sample(version,requester,reviewer,"REQ-20260817-C9B4E2",SubmissionStatus.APPROVED,"Brightline Studio","42","Marketing","2026-09-01",null);sample(version,requester,reviewer,"REQ-20260816-F3A8C6",SubmissionStatus.REJECTED,"Harbor Facilities","320","Facilities","2026-08-28","Please attach the updated compliance certificate before resubmitting.");}
 private AppUser user(String email,String name,Role role){var u=new AppUser();u.setEmail(email);u.setDisplayName(name);u.setRole(role);u.setPasswordHash(passwords.encode("IntakeFlow@2026"));return u;}
 private void add(FormVersion v,String key,String label,String description,FieldType type,boolean required,List<String> options){var f=new FormField();f.setFieldKey(key);f.setLabel(label);f.setDescription(description);f.setFieldType(type);f.setRequired(required);f.setPositionIndex(v.getFields().size());for(int i=0;i<options.size();i++){var o=new FieldOption();o.setValue(options.get(i));o.setPositionIndex(i);f.addOption(o);}v.addField(f);}
 private void sample(FormVersion v,AppUser requester,AppUser reviewer,String ref,SubmissionStatus status,String... values){var s=new Submission();s.setReferenceCode(ref);s.setFormVersion(v);s.setRequester(requester);s.setStatus(status);s.setSubmittedAt(Instant.now().minus(Duration.ofDays(status==SubmissionStatus.SUBMITTED?1:3)));if(status==SubmissionStatus.REJECTED)s.setRejectionComment(values[4]);for(int i=0;i<4;i++){var a=new SubmissionAnswer();a.setField(v.getFields().get(i));a.setValue(values[i]);s.addAnswer(a);}var submitted=event(requester,"SUBMITTED",SubmissionStatus.DRAFT,SubmissionStatus.SUBMITTED,null);s.addEvent(submitted);if(status==SubmissionStatus.APPROVED){s.setReviewedAt(Instant.now().minus(Duration.ofDays(2)));s.addEvent(event(reviewer,"APPROVED",SubmissionStatus.SUBMITTED,status,null));}if(status==SubmissionStatus.REJECTED){s.setReviewedAt(Instant.now().minus(Duration.ofDays(1)));s.addEvent(event(reviewer,"REJECTED",SubmissionStatus.SUBMITTED,status,values[4]));}submissions.save(s);}
 private WorkflowEvent event(AppUser actor,String action,SubmissionStatus from,SubmissionStatus to,String comment){var e=new WorkflowEvent();e.setActor(actor);e.setAction(action);e.setFromStatus(from);e.setToStatus(to);e.setComment(comment);e.setCreatedAt(Instant.now().minus(Duration.ofDays(1)));return e;}
}
